### ISSUE TITLE
Harbor continuely polling restart

### ISSUE THREAD

**Issue by tattack99** [kthcloud/landing-frontend#146]
**Describe the bug**
Restart multiple times. Seems to be Harbor polling restart. Cannot push with docker CI. 

**To Reproduce**
1. Create new kubernetees in CBH cloud. 
2. Wait
3. You can try to push using CI docker command provided. But it still keeps restarting. 

**Expected behavior**
My docker image is being uploaded to cloud and the server start running with that image. 

**Screenshots**
<img width="1128" alt="Skärmavbild 2024-01-02 kl  09 54 49" src="https://github.com/kthcloud/landing-frontend/assets/62747925/4f9d0a7e-4703-48d8-a17c-c1694856051f">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version 120.0.6099.129 (Officiell version) (x86_64)

**Additional context**

**Comment by pierrelefevre** [comment]
@saffronjam do we have timestamps available for the build logs? 

Suspecting this is actually old logs and the docker image is not working for some reason, but the logs aren't making their way back to you.

**Comment by tattack99** [comment]
link to deplyoment:
https://cloud.cbh.kth.se/edit/deployment/53003e12-5050-4a37-8737-7adaa7134175

**Comment by saffronjam** [comment]
This should be resolved now, I think the logs were stale, and that the deployment was in fact working.
And it seems to have been caused by an overloaded pod in our backend (too many "collect-logs-threads"), which has been scaled up.

I have added timestamps for the build logs too, so it is easier to trace in the future 🥰

**Comment by tattack99** [comment]
The solution seem to work for the deplyoment i previously linked. 
But the issue persist when creating a new deplyoment. 

Same issue on this deployment:
https://cloud.cbh.kth.se/edit/deployment/8aa5c6ce-2868-4b83-b5c3-5c3ad4cc4916
<img width="1133" alt="Skärmavbild 2024-01-02 kl  15 16 27" src="https://github.com/kthcloud/landing-frontend/assets/62747925/bdfdc0f0-9d53-4a1f-8ea9-08a7783c0672">

**Comment by pierrelefevre** [comment]
Closing this issue for now, feel free to reach out in the support channel on Discord if the issue persists.
